import Header from "../../components/Header"
import Banner from "../../components/Banner"
import Footer from "../../components/Footer"
import Providers from "../../components/providers"
import '../../src/styles/globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode,
  
}) {
  return (
    <html lang="en">
      <body className='max-w-7xl mx-auto'>
      
        <Providers>
        <Header/>
        <Banner/>
          {children}
          </Providers>
        <Footer/>
      </body>
    </html>
  )
}
